name: Build and Deploy Code

on: [push, pull_request]
# on:
#   push:
#     branches:
#       - "main"
#       - "anotherbranch"
#   pull_request:
#     branches:
#       - "main"
#       - 

#env

jobs:
  job1:
    environment:
      name: testing
    env:
      DB_HOST: ${{secrets.DB_HOST}}
      #DB_HOST: postgres / localhost
      DB_PORT: ${{secrets.DB_PORT}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_SCHEMA: ${{secrets.DB_SCHEMA}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}

    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_DB: ${{secrets.DB_NAME}}_test
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
        ports:
        - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.12.3
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.3"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest